services:
  - type: web
    name: dnd-travels-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OUTPUT_DIR
        value: ./output
      - key: LOG_LEVEL
        value: INFO
